"""editorial_quizzes

Revision ID: 0006_editorial_quizzes
Revises: 0005_assessment_submissions
Create Date: 2026-10-04 04:13:09.177958+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0006_editorial_quizzes"
down_revision: str | None = "0005_assessment_submissions"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quiz_drafts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("teacher_id", sa.UUID(), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("current_version", sa.Integer(), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("current_version >= 1", name="ck_quiz_draft_version"),
        sa.ForeignKeyConstraint(["subject_id"], ["subjects.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["teacher_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_quiz_drafts_teacher_id"), "quiz_drafts", ["teacher_id"], unique=False)
    op.create_table(
        "quiz_draft_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("draft_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("reviewer_id", sa.UUID(), nullable=True),
        sa.Column("review_revision", sa.Integer(), nullable=False),
        sa.Column("source_revisions", sa.JSON(), nullable=False),
        sa.Column("scoring_policy", sa.String(length=30), nullable=False),
        sa.Column("release_policy", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "release_policy IN ('after_submission','after_due')", name="ck_editorial_release"
        ),
        sa.CheckConstraint(
            "state IN ('draft','in_review','approved','rejected','published')",
            name="ck_editorial_version_state",
        ),
        sa.CheckConstraint("version >= 1 AND review_revision >= 0", name="ck_editorial_revision"),
        sa.ForeignKeyConstraint(["draft_id"], ["quiz_drafts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["reviewer_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["subject_id"], ["subjects.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("draft_id", "version", name="uq_quiz_draft_version"),
    )
    op.create_index(
        op.f("ix_quiz_draft_versions_draft_id"), "quiz_draft_versions", ["draft_id"], unique=False
    )
    op.create_index(
        op.f("ix_quiz_draft_versions_reviewer_id"),
        "quiz_draft_versions",
        ["reviewer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_quiz_draft_versions_state"), "quiz_draft_versions", ["state"], unique=False
    )
    op.create_table(
        "quiz_assignments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("version_id", sa.UUID(), nullable=False),
        sa.Column("class_id", sa.UUID(), nullable=False),
        sa.Column("teacher_id", sa.UUID(), nullable=False),
        sa.Column("opens_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_closed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "opens_at IS NULL OR due_at IS NULL OR opens_at < due_at", name="ck_assignment_schedule"
        ),
        sa.ForeignKeyConstraint(["class_id"], ["classrooms.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["teacher_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["version_id"], ["quiz_draft_versions.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_quiz_assignments_class_id"), "quiz_assignments", ["class_id"], unique=False
    )
    op.create_index(
        op.f("ix_quiz_assignments_teacher_id"), "quiz_assignments", ["teacher_id"], unique=False
    )
    op.create_index(
        op.f("ix_quiz_assignments_version_id"), "quiz_assignments", ["version_id"], unique=False
    )
    op.create_table(
        "quiz_draft_questions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("version_id", sa.UUID(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("narration", sa.Text(), nullable=False),
        sa.Column("options", sa.JSON(), nullable=False),
        sa.Column("correct_option_id", sa.String(length=40), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("concept_id", sa.UUID(), nullable=True),
        sa.Column("difficulty", sa.String(length=20), nullable=False),
        sa.CheckConstraint(
            "difficulty IN ('easy','medium','hard')", name="ck_editorial_question_difficulty"
        ),
        sa.CheckConstraint(
            "order_index >= 1 AND order_index <= 20", name="ck_editorial_question_order"
        ),
        sa.ForeignKeyConstraint(["concept_id"], ["concepts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["version_id"], ["quiz_draft_versions.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version_id", "order_index", name="uq_editorial_question_order"),
    )
    op.create_index(
        op.f("ix_quiz_draft_questions_version_id"),
        "quiz_draft_questions",
        ["version_id"],
        unique=False,
    )
    op.create_table(
        "quiz_review_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("version_id", sa.UUID(), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("reviewer_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["reviewer_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["version_id"], ["quiz_draft_versions.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_quiz_review_events_version_id"), "quiz_review_events", ["version_id"], unique=False
    )
    op.create_table(
        "assignment_attempts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("assignment_id", sa.UUID(), nullable=False),
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("correct_count", sa.Integer(), nullable=True),
        sa.Column("total_questions", sa.Integer(), nullable=False),
        sa.Column("submission_key", sa.UUID(), nullable=True),
        sa.Column("submission_revision", sa.Integer(), nullable=True),
        sa.Column("receipt", sa.JSON(), nullable=True),
        sa.CheckConstraint(
            "state IN ('in_progress','submitted')", name="ck_assignment_attempt_state"
        ),
        sa.CheckConstraint("revision >= 0", name="ck_assignment_attempt_revision"),
        sa.CheckConstraint(
            "score IS NULL OR (score >= 0 AND score <= 100)", name="ck_assignment_score"
        ),
        sa.ForeignKeyConstraint(["assignment_id"], ["quiz_assignments.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["student_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("assignment_id", "student_id", name="uq_assignment_student_attempt"),
    )
    op.create_index(
        op.f("ix_assignment_attempts_assignment_id"),
        "assignment_attempts",
        ["assignment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assignment_attempts_student_id"),
        "assignment_attempts",
        ["student_id"],
        unique=False,
    )
    op.create_table(
        "assignment_answers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("attempt_id", sa.UUID(), nullable=False),
        sa.Column("question_id", sa.UUID(), nullable=False),
        sa.Column("option_id", sa.String(length=40), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=True),
        sa.Column("feedback", sa.Text(), nullable=True),
        sa.Column("saved_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["attempt_id"], ["assignment_attempts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["question_id"], ["quiz_draft_questions.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("attempt_id", "question_id", name="uq_assignment_answer"),
    )
    op.create_index(
        op.f("ix_assignment_answers_attempt_id"), "assignment_answers", ["attempt_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_assignment_answers_attempt_id"), table_name="assignment_answers")
    op.drop_table("assignment_answers")
    op.drop_index(op.f("ix_assignment_attempts_student_id"), table_name="assignment_attempts")
    op.drop_index(op.f("ix_assignment_attempts_assignment_id"), table_name="assignment_attempts")
    op.drop_table("assignment_attempts")
    op.drop_index(op.f("ix_quiz_review_events_version_id"), table_name="quiz_review_events")
    op.drop_table("quiz_review_events")
    op.drop_index(op.f("ix_quiz_draft_questions_version_id"), table_name="quiz_draft_questions")
    op.drop_table("quiz_draft_questions")
    op.drop_index(op.f("ix_quiz_assignments_version_id"), table_name="quiz_assignments")
    op.drop_index(op.f("ix_quiz_assignments_teacher_id"), table_name="quiz_assignments")
    op.drop_index(op.f("ix_quiz_assignments_class_id"), table_name="quiz_assignments")
    op.drop_table("quiz_assignments")
    op.drop_index(op.f("ix_quiz_draft_versions_state"), table_name="quiz_draft_versions")
    op.drop_index(op.f("ix_quiz_draft_versions_reviewer_id"), table_name="quiz_draft_versions")
    op.drop_index(op.f("ix_quiz_draft_versions_draft_id"), table_name="quiz_draft_versions")
    op.drop_table("quiz_draft_versions")
    op.drop_index(op.f("ix_quiz_drafts_teacher_id"), table_name="quiz_drafts")
    op.drop_table("quiz_drafts")
    # ### end Alembic commands ###
