"""Finite public menu catalog. Never accept guest-provided synthesis text."""
MENU_AUDIO = {
    "welcome": (
        "Selamat datang di KODMOD. Pilih suara KODMOD atau suara perangkat. Tekan contoh suara untuk mendengarkan. Pembaca menu dapat dimatikan. Suara Tutor tetap aktif saat belajar.",
        "Welcome to KODMOD. Choose the KODMOD voice or your device voice. Press preview to listen. You can turn menu reading off. Your Tutor still speaks while you learn.",
    ),
    "preview": ("Halo, ini suara KODMOD. Saya akan menemanimu belajar, satu langkah demi satu langkah.",
                "Hello, this is the KODMOD voice. I will help you learn, one step at a time."),
    "home": ("Beranda", "Home"),
    "about": ("Tentang KODMOD", "About KODMOD"),
    "how": ("Cara belajar", "How to learn"),
    "features": ("Fitur", "Features"),
    "faq": ("Pertanyaan umum", "Frequently asked questions"),
    "login": ("Masuk", "Sign in"),
    "register": ("Daftar", "Create an account"),
    "username": ("Username. Isi nama pengguna akunmu.", "Username. Enter your account username."),
    "password": ("Kata sandi", "Password"),
    "full-name": ("Nama lengkap", "Full name"),
    "role": ("Pilih peran siswa atau guru", "Choose student or teacher"),
    "dashboard": ("Dashboard", "Dashboard"),
    "classes": ("Kelas saya", "My classes"),
    "materials": ("Pustaka materi", "Learning library"),
    "tutor": ("Tutor AI", "AI Tutor"),
    "practice": ("Latihan", "Practice"),
    "assignments": ("Tugas dari guru", "Teacher assignments"),
    "progress": ("Progres saya", "My progress"),
    "quizzes": ("Kuis dan penugasan", "Quizzes and assignments"),
    "review": ("Review kuis", "Quiz reviews"),
    "analytics": ("Analitik siswa", "Student analytics"),
    "users": ("Pengguna", "Users"),
    "activity": ("Aktivitas dan layanan", "Activity and services"),
    "sound": ("Pengaturan suara dan bahasa", "Voice and language settings"),
    "sound-on": ("Suara menu aktif", "Menu voice is on"),
    "sound-off": ("Suara menu mati", "Menu voice is off"),
    "language": ("Bahasa. Pilih Bahasa Indonesia atau Inggris.", "Language. Choose Indonesian or English."),
    "navigation": ("Buka navigasi", "Open navigation"),
    "language-changed": ("Bahasa telah berubah ke Bahasa Indonesia.", "Language changed to English."),
    "logout": ("Keluar dari akun", "Sign out"),
}
